delgadoapp/apps/projetos/urls.py
from django.urls import path
from . import views

app_name = 'projetos'

urlpatterns = [
    path('', views.list_projetos, name='list_projetos'),
    path('excluir-item/<int:id_projeto>/', views.delete_projeto, name='delete_projeto'),
    path('adicionar-item/', views.add_projeto, name='add_projeto'),
    path('editar-status/<int:id_projeto>/', views.edit_projeto, name='edit_projeto'),
]

delgadoapp/delgadoapp/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('generos/', include('generos.urls', namespace='generos')),
    path('pagamentos/', include('pagamentos.urls', namespace='pagamentos')),
    path('funcionarios/', include('funcionarios.urls', namespace='funcionarios')),
    path('projetos/', include('projetos.urls', namespace='projetos')),
    path('contas/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delgadoapp/apps/projetos/models.py
from django.db import models

class Projeto(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField('Descricao', max_length=300)
    project = models.CharField('Projeto', max_length=50)

    class Meta:
        verbose_name = 'Projeto'
        verbose_name_plural = 'Projetos'
        ordering =['id']

    def __str__(self):
        return "%s" % (self.project) 

delgadoapp/apps/projetos/forms.py
from django import forms
from .models import Projeto

class ProjetoForm(forms.ModelForm):
    
    class Meta:
        model = Projeto
        exclude = ('projeto', 'created_on' , 'updated_on')

delgadoapp/apps/projetos/views.py
from ast import Or
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ProjetoForm
from .models import Projeto

def list_projetos(request):
    template_name = 'projetos/list_projetos.html'
    projetos = Projeto.objects.filter()
    context = {
        'projetos': projetos,
    }
    return render(request, template_name, context)

def add_projeto(request):
    template_name = 'projetos/add_projeto.html'
    context = {}
    if request.method == 'POST':
        form = ProjetoForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('projetos:list_projetos')
    form = ProjetoForm()
    context['form'] = form
    return render(request, template_name, context)

def delete_projeto(request, id_projeto):
    projeto = Projeto.objects.get(id=id_projeto)
    projeto.delete()
    return redirect('projetos:list_projetos')

def edit_projeto(request, id_projeto):
    template_name = 'projetos/add_projeto.html'
    context ={}
    projeto = get_object_or_404(Projeto, id=id_projeto)
    if request.method == 'POST':
        form = ProjetoForm(request.POST, instance=projeto)
        if form.is_valid():
            form.save()
            return redirect('projetos:list_projetos')
    form = ProjetoForm(instance=projeto)
    context['form'] = form
    return render(request, template_name, context)

delgadoapp/templates/projetos/add_projeto.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Item de Pedido - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Adicionar Projeto</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <!-- <div class="form-group">
                    <label for="{{ form.quantity.id_for_label }}">Departamento</label>
                    {{ form.project|add_class:"form-control" }}
                </div> -->
                <div class="form-group">
                    <label for="{{ form.unitary_price.id_for_label }}">Nome do projeto</label>
                    {{ form.project|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.pagamento.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

delgadoapp/templates/projetos/adiciona_projetos.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Rede Social - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Genêros</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.name.id_for_label }}"> Genêro</label>
                   {{ form.name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descricao</label>
                    {{ form.description|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

delgadoapp/templates/projetos/list_projetos.html
{% extends 'base.html' %}

{% block title %}

    Lista de Projetos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Projetos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'projetos:add_projeto' %}">Criar novo projeto</a>
                <br />
            <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome do projeto</th>
                    <th scope="col">Descrição</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for projeto in projetos %}
                        <tr>
                            <th scope="row">
                                {{ projeto.id }}
                            </th>
                            <td>
                                {{ projeto.project }}
                            </td>
                            <td>
                                {{ projeto.description }}
                            </td>
                            <td>
                            </td>
                            <td>
                                <br /><br />
                            </td>
                            <td>
                                <a href="{% url 'projetos:edit_projeto' projeto.id %}" class="btn btn-primary btn-sm ">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'projetos:delete_projeto' projeto.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}

delgadoapp/templates/projetos/lista_projetos.html
{% extends 'base.html' %}

{% block title %}

    Lista de Genero - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Genêros</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'projetos:adiciona_projetos' %}">Cadastrar novo genero</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Genêro</th>
                    <th scope="col">Descricao</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for projeto in projetos %}
                        <tr>
                            <th scope="row">{{ projeto.id }}</th>
                            <td>{{ projeto.name }}</td>
                            <td>{{ projeto.description }}</td>
                            <td>
                                <a href="{% url 'projetos:edit_projetos' projeto.id %}" class="btn btn-primary btn-sm">Editar</a>
                                <a href="{% url 'projetos:delete_projetos' projeto.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}