delgadoapp/apps/funcionarios/urls.py
from django.urls import path
from . import views

app_name = 'funcionarios'

urlpatterns = [
    path('', views.list_funcionarios, name='list_funcionarios'),
    path('adicionar/', views.add_funcionario, name='add_funcionario'),
    path('editar/<int:id_funcionario>/', views.edit_funcionario, name='edit_funcionario'),
    path('excluir/<int:id_funcionario>/', views.delete_funcionario, name='delete_funcionario'),
    path('buscar/', views.search_funcionarios, name='search_funcionarios'),
]

delgadoapp/apps/pagamentos/urls.py
from django.urls import path
from . import views

app_name = 'pagamentos'

urlpatterns = [
    path('', views.list_pagamentos, name='list_pagamentos'),
    path('adicionar/', views.add_pagamento, name='add_pagamento'),
    path('editar/<int:id_pagamento>/', views.edit_pagamento, name='edit_pagamento'),
    path('excluir/<int:id_pagamento>/', views.delete_pagamento, name='delete_pagamento'),
]

delgadoapp/delgadoapp/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('generos/', include('generos.urls', namespace='generos')),
    path('pagamentos/', include('pagamentos.urls', namespace='pagamentos')),
    path('funcionarios/', include('funcionarios.urls', namespace='funcionarios')),
    path('projetos/', include('projetos.urls', namespace='projetos')),
    path('contas/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delgadoapp/apps/funcionarios/models.py
from typing import Tuple
from django.db import models
from generos.models import Genero
from projetos.models import Projeto

class Funcionario(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    first_name = models.CharField('Nome', max_length=50)
    # last_name = models.CharField('Sobrenome', max_length=100) 
    address = models.CharField('Endereco', max_length=200)   
    cell_phone = models.CharField('Telefone celular', max_length=20)
    email = models.EmailField('E-mail',null=False, blank=False)

    JOB_CHOICES = (
        ('TL', 'Tech Lead'),
        ('PM', 'Product Manager'),
        ('ES', 'Engenheiro de Software'),
    )
    job = models.CharField('Profissao', max_length=2, choices=JOB_CHOICES)
    DEPARTAMENT_CHOICES = (
        ('PEX', 'Investment Plataform'),
        ('BRK', 'Broker'),
        ('OB', 'Onboarding'),
        ('TR', 'Trade'),
    )
    departament = models.CharField('Departamento', max_length=3, choices=DEPARTAMENT_CHOICES)

    gender = models.ForeignKey( Genero, on_delete=models.CASCADE)
    project = models.ManyToManyField(Projeto, through='FuncionarioProject', blank=True)
    
    class Meta:
        verbose_name = 'Funcionario'
        verbose_name_plural = 'Funcionarios'
        ordering =['id']

    def __str__(self):
        return self.first_name

class FuncionarioGenero(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    genero = models.ForeignKey(Genero, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Genero'
        verbose_name_plural = 'Generos'
        ordering =['id']

    def __str__(self):
        return self.genero.name


class FuncionarioProject(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.CASCADE)
    project = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Funcionário do projeto'
        verbose_name_plural = 'Funcionários dos projetos'
        ordering =['id']

    def __str__(self):
        return self.project.name

delgadoapp/apps/funcionarios/forms.py
from django import forms
from .models import Funcionario

class FuncionarioForm(forms.ModelForm):

    class Meta:
        model = Funcionario
        exclude = ('created_on' , 'updated_on',)

delgadoapp/apps/funcionarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import FuncionarioForm
from .models import Genero, FuncionarioGenero, Funcionario

# Create your views here.
def add_funcionario(request):
    template_name = 'funcionarios/add_funcionario.html'
    context = {}
    if request.method == 'POST':
        form = FuncionarioForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('funcionarios:list_funcionarios')
    form = FuncionarioForm()
    context['form'] = form
    return render(request, template_name, context)

def list_funcionarios(request):
    template_name = 'funcionarios/list_funcionarios.html'
    funcionario_genero = FuncionarioGenero.objects.filter()
    generos = Genero.objects.filter()
    funcionarios = Funcionario.objects.filter()
    context = {
        'funcionarios': funcionarios,
        'generos': generos,
        'funcionario_generos': funcionario_genero
    }
    return render(request, template_name, context)

def edit_funcionario(request, id_funcionario):
    template_name = 'funcionarios/add_funcionario.html'
    context ={}
    funcionario = get_object_or_404(Funcionario, id=id_funcionario)
    if request.method == 'POST':
        form = FuncionarioForm(request.POST, instance=funcionario)
        if form.is_valid():
            form.save()
            return redirect('funcionarios:list_funcionarios')
    form = FuncionarioForm(instance=funcionario)
    context['form'] = form
    return render(request, template_name, context)

def delete_funcionario(request, id_funcionario):
    funcionario = Funcionario.objects.get(id=id_funcionario)
    funcionario.delete()
    return redirect('funcionarios:list_funcionarios')

def search_funcionarios(request):
    template_name = 'funcionarios/list_funcionarios.html'
    query = request.GET.get('query')
    funcionario_generos = FuncionarioGenero.objects.filter()
    generos = Genero.objects.filter()
    funcionarios = Funcionario.objects.filter(last_name__icontains=query)
    context = {
        'funcionarios': funcionarios,
        'generos': generos,
        'funcionario_generos': funcionario_generos
    }
    return render(request,template_name, context)

delgadoapp/templates/funcionarios/add_funcionario.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar funcionario - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Funcionário</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.first_name.id_for_label }}">Nome</label>
                   {{ form.first_name|add_class:"form-control" }}
                </div>
                <!-- <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div> -->
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                  <label for="{{ form.cell_phone.id_for_label }}">Telefone</label>
                  {{ form.cell_phone|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                    {{ form.email|add_class:"form-control" }}
                </div>
                <!-- <div class="form-group">
                    <label for="{{ form.gender.id_for_label }}">Genêro</label>
                    {{ form.gender|add_class:"form-control" }}
                </div> -->
                <div class="form-group">
                    <label for="{{ form.job.id_for_label }}">Profissão</label>
                    {{ form.job|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.department.id_for_label }}">Departamento</label>
                    {{ form.departament|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.gender.id_for_label }}">Genero</label>
                    {{ form.gender|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.project.id_for_label }}">Projetos</label>
                    {{ form.project|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

delgadoapp/templates/funcionarios/list_funcionarios.html
{% extends 'base.html' %}

{% block title %}

    Lista de Funcionários - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Funcionários</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'funcionarios:add_funcionario' %}">Cadastrar novo funcionário</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Endereço</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Profissão</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Genero</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for funcionario in funcionarios %}
                        <tr>
                            <th scope="row">{{ funcionario.id }}</th>
                            <td>{{ funcionario.first_name }}</td>
                            <td>{{ funcionario.address }}</td>
                            <td>{{ funcionario.cell_phone }}</td>
                            <td>{{ funcionario.email }}</td>
                            <td>{{ funcionario.job }}</td>
                            <td>{{ funcionario.departament }}</td>
                            <td>{{ funcionario.gender }}</td>
                            <td>
                             </td>
                            <td>
                                <a href="{% url 'funcionarios:edit_funcionario' funcionario.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td>
                                <a href="{% url 'funcionarios:delete_funcionario' funcionario.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                            <td>   
                                 <a href="{% url 'pagamentos:add_pagamento'%}" class="btn btn-sm btn-primary ">Pagamento</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}