delgadoapp/apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('novo-usuario/',views.add_user, name='add_user'),
    path('login/',views.user_login, name='user_login'),
    path('sair/',views.user_logout, name='user_logout'),
    path('alterar-senha/',views.user_change_password, name='user_change_password'),
    path('alterar-usuario/<username>/',views.user_change_information, name='user_change_information'),
]

delgadoapp/apps/generos/urls.py
from django.urls import path
from . import views

app_name = 'generos'

urlpatterns = [
    path('', views.lista_generos, name='lista_generos'),
    path('adicionar/', views.adiciona_generos, name='adiciona_generos'),
    path('editar/<int:id_genero>/', views.edit_generos, name='edit_generos'),
    path('excluir/<int:id_genero>/', views.delete_generos, name='delete_generos'),
]

delgadoapp/apps/pagamentos/urls.py
from django.urls import path
from . import views

app_name = 'pagamentos'

urlpatterns = [
    path('', views.list_pagamentos, name='list_pagamentos'),
    path('adicionar/', views.add_pagamento, name='add_pagamento'),
    path('editar/<int:id_pagamento>/', views.edit_pagamento, name='edit_pagamento'),
    path('excluir/<int:id_pagamento>/', views.delete_pagamento, name='delete_pagamento'),
]

delgadoapp/apps/projetos/urls.py
from django.urls import path
from . import views

app_name = 'projetos'

urlpatterns = [
    path('', views.list_projetos, name='list_projetos'),
    path('excluir-item/<int:id_projeto>/', views.delete_projeto, name='delete_projeto'),
    path('adicionar-item/', views.add_projeto, name='add_projeto'),
    path('editar-status/<int:id_projeto>/', views.edit_projeto, name='edit_projeto'),
]

delgadoapp/delgadoapp/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('generos/', include('generos.urls', namespace='generos')),
    path('pagamentos/', include('pagamentos.urls', namespace='pagamentos')),
    path('funcionarios/', include('funcionarios.urls', namespace='funcionarios')),
    path('projetos/', include('projetos.urls', namespace='projetos')),
    path('contas/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delgadoapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %} App{% endblock title %}</title>
</head>
<body>

    <!-- INICIO: Bloco do Bootstrap a ser incluido -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'funcionarios:list_funcionarios' %}"> Gestão de Pessoas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample05">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown05">
                        <a class="dropdown-item" href="{% url 'funcionarios:list_funcionarios' %}">Funcionários</a>
                        <a class="dropdown-item" href="{% url 'projetos:list_projetos' %}">Projetos</a>
                        <a class="dropdown-item" href="{% url 'pagamentos:list_pagamentos' %}">Pagamentos</a>
                        <a class="dropdown-item" href="{% url 'generos:lista_generos' %}">Genero</a>
                    </div>
                </li>
            </ul>
            <form action="{% url 'funcionarios:search_funcionarios' %}" method="GET" class="form-inline my-2 my-md-0" style="margin-right: 10px">
                <input class="form-control" name="query" type="text" placeholder="Pesquisar" aria-label="Buscar" style="margin-right: 10px">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Buscar</button>
            </form>
            
        <!--{% if user.is_authenticated %}-->
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown05" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name|default:user.username }}</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown05">
                            <a class="dropdown-item" href="{% url 'accounts:user_change_information' user.username %}">Conta</a>
                            <a class="dropdown-item" href="{% url 'accounts:user_change_password' %}">Trocar senha</a>
                            <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Sair</a>
                        </div>
                    </li>
                </ul>
        </div>
        <!-- {% endif %} -->
    </nav>
    <!-- FIM: Bloco do Bootstrap a ser incluido -->

    {% block body %}
    
    {% endblock body %}
    
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>